<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run()
    {
        DB::table('products')->delete();
        DB::table('products')->truncate();
        DB::table('products')->insert([
            //Keyboard
            [
                'product_name' => 'Bàn phím cơ không dây E-DRA EK314W Blue switch (104 phím, Wireless 2.4GHz, Bluetooth, E-dra Switch, Màu Đen)',
                'slug_product' => 'ban-phim-co-khong-day-e-dra-ek314w-blue-switch-104-phim-wireless-24ghz-bluetooth-e-dra-switch-mau-den',
                'picture' => 'https://philong.com.vn/media/product/30086-philong-ban-phim-co-khong-day-e-dra-ek314w-mau-den.jpg',
                'short_description' => 'Kết nối: Wireless 2.4G, BluetoothKeycaps: ABS, Layout: 104 phímSwitch: E-dra Switch (Blue / Red / Brown), Đèn nền: Không',
                'detailed_description' => 'Kết nối: Wireless 2.4G, BluetoothKeycaps: ABS, Layout: 104 phímSwitch: E-dra Switch (Blue / Red / Brown), Đèn nền: Không',
                'quantity' => 10,
                'status' => 1,
                'price_sell' => 599000 / 24000,
                'price_discount' => 499000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_name' => 'Bàn phím cơ Gaming không dây Logitech G Pro X TKL LIGHTSPEED Black, GX Tactile Switch (920-012137))',
                'slug_product' => 'ban-phim-co-gaming-khong-day-logitech-g-pro-x-tkl-lightspeed-black-gx-tactile-switch-920-012137',
                'picture' => 'https://philong.com.vn/media/product/31126-ban-phim-co-khong-day-logitech-g-pro-x-tkl-lightspeed-black-920-012137-philong--2-.jpg',
                'short_description' => 'Kết nối Bluetooth Wireless với công nghệ LIGHTSPEED cho tốc độ phản hồi chỉ 1msSử dụng Switch GX Tactile độc quyền của LogitechCông nghệ LIGHTSYNC RGB 16.8 triệu màu mang lại cảm giác đồng điệu về hình ảnh và âm thanh với trò chơiThời lượng pin lên đến 50 giờ cho một lần sạc đầy12 phím F có thể lập trìnhKhoảng cách hành trình: 1.9 mm - 2.0 mm2 tùy chọn màu sắc: Đen/Trắng',
                'detailed_description' => 'Kết nối Bluetooth Wireless với công nghệ LIGHTSPEED cho tốc độ phản hồi chỉ 1msSử dụng Switch GX Tactile độc quyền của LogitechCông nghệ LIGHTSYNC RGB 16.8 triệu màu mang lại cảm giác đồng điệu về hình ảnh và âm thanh với trò chơiThời lượng pin lên đến 50 giờ cho một lần sạc đầy12 phím F có thể lập trìnhKhoảng cách hành trình: 1.9 mm - 2.0 mm2 tùy chọn màu sắc: Đen/Trắng',
                'quantity' => 5,
                'status' => 1,
                'price_sell' => 5790000 / 24000,
                'price_discount' => 4790000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Bàn phím cơ không dây FL-Esports CMK75SAM Desert Grey, FLCMMK Ice Violet Switch (3 mode, Hotswap, Gasket mount, Núm xoay, Màn hiển thị, Led RGB)',
                'slug_product' => 'ban-phim-co-khong-day-fl-esports-cmk75sam-desert-grey-flcmmk-ice-violet-switch-3-mode-hotswap-gasket-mount-num-xoay-man-hien-thi-led-rgb',
                'picture' => 'https://philong.com.vn/media/product/30492-ban-phim-co-fl-esports-cmk75sam-desert-grey-philong--1-.jpg',
                'short_description' => 'Layout 75%, 82 nút phím (81 phím + 1 núm xoay)3 chế độ kết nối: USB, 2.4GHz, BluetoothKeycap: PBT doubleshot, FSA profileMạch xuôi, Gasket Mount, Plate PC, Trang bị sẵn đệm tiêu âmSwitch: FLCMMK Ice Violet, Hỗ trợ Hot SwapPin: 3000mAh, Led: RGB',
                'detailed_description' => 'Layout 75%, 82 nút phím (81 phím + 1 núm xoay)3 chế độ kết nối: USB, 2.4GHz, BluetoothKeycap: PBT doubleshot, FSA profileMạch xuôi, Gasket Mount, Plate PC, Trang bị sẵn đệm tiêu âmSwitch: FLCMMK Ice Violet, Hỗ trợ Hot SwapPin: 3000mAh, Led: RGB',
                'quantity' => 3,
                'status' => 1,
                'price_sell' => 349000 / 24000,
                'price_discount' => 249000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Bàn phím cơ không dây CIDOO V75 Pro Tri-mode Matt Grey Switch (USB-C, Bluetooth, 2.4Ghz, Vỏ nhôm CNC)',
                'slug_product' => 'ban-phim-co-khong-day-cidoo-v75-pro-tri-mode-matt-grey-switch-usb-c-bluetooth-24ghz-vo-nhom-cnc',
                'picture' => 'https://philong.com.vn/media/product/30725-ban-phim-co-khong-day-cidoo-v75-pro-tri-mode-matt-grey-switch-philong--1-.jpg',
                'short_description' => 'Layout 75%, Có núm xoay chỉnh âm lượng3 chế độ kết nối: Cáp USB-C, Bluetooth, 2.4GhzKeycap: PBT Dyesub, Cherry profileMạch xuôi, gasket mount, hỗ trợ hotswap thay switch dễ dàngSwitch: Cidoo Matt GreyPin: 3000mAh; Led: RGB',
                'detailed_description' => 'Layout 75%, Có núm xoay chỉnh âm lượng3 chế độ kết nối: Cáp USB-C, Bluetooth, 2.4GhzKeycap: PBT Dyesub, Cherry profileMạch xuôi, gasket mount, hỗ trợ hotswap thay switch dễ dàngSwitch: Cidoo Matt GreyPin: 3000mAh; Led: RGB',
                'quantity' => 8,
                'status' => 1,
                'price_sell' => 4190000 / 24000,
                'price_discount' => 3190000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Bàn phím cơ Asus TUF Gaming K3 (Full size, Red Switch, USB 2.0, Có kê tay)',
                'slug_product' => 'ban-phim-co-asus-tuf-gaming-k3-full-size-red-switch-usb-20-co-ke-tay',
                'picture' => 'https://philong.com.vn/media/product/29786-phi-long-ban-phim-co-gaming-asus-tuf-k3-red-switch-01.jpg',
                'short_description' => 'Bàn phím cơ RGB cơ với tuổi thọ 50 triệu lần nhấn phím cho hiệu suất lâu dàiChống kẹt phím 100% với công nghệ N-key rollover (NKRO) giúp người dùng có thể ấn đồng thời nhiều phím cùng lúc, phản hồi cực tốtKết hợp các phím dễ dàng để điều chỉnh nhanh các chức năng đa phương tiệnVới cổng USB 2.0 mở rộng giúp kết nối nhanh các thiết bị sử dụng hàng ngày như chuột, ổ đĩa USB, sạc điện thoại thông minh hoặc máy tính bảngVỏ bề mặt bằng hợp kim nhôm bền bỉ với thời gianTám phím có thể lập trình đầy đủ để gán macro một cách nhanh chóng và lưu trữ các tinh chỉnh trên bộ nhớ tích hợpPhím đèn nền độc lập trang bị công nghệ Aura Sync RGB LED để tạo ra số lượng tùy chọn cá nhân hóa không giới hạn',
                'detailed_description' => 'Bàn phím cơ RGB cơ với tuổi thọ 50 triệu lần nhấn phím cho hiệu suất lâu dàiChống kẹt phím 100% với công nghệ N-key rollover (NKRO) giúp người dùng có thể ấn đồng thời nhiều phím cùng lúc, phản hồi cực tốtKết hợp các phím dễ dàng để điều chỉnh nhanh các chức năng đa phương tiệnVới cổng USB 2.0 mở rộng giúp kết nối nhanh các thiết bị sử dụng hàng ngày như chuột, ổ đĩa USB, sạc điện thoại thông minh hoặc máy tính bảngVỏ bề mặt bằng hợp kim nhôm bền bỉ với thời gianTám phím có thể lập trình đầy đủ để gán macro một cách nhanh chóng và lưu trữ các tinh chỉnh trên bộ nhớ tích hợpPhím đèn nền độc lập trang bị công nghệ Aura Sync RGB LED để tạo ra số lượng tùy chọn cá nhân hóa không giới hạn',
                'quantity' => 3,
                'status' => 1,
                'price_sell' => 2850000 / 24000,
                'price_discount' => 1850000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Bàn phím không dây Bluetooth Logitech Pebble Keys 2 K380s, Tonal White (920-011754)',
                'slug_product' => 'ban-phim-khong-day-bluetooth-logitech-pebble-keys-2-k380s-tonal-white-920-011754',
                'picture' => 'https://philong.com.vn/media/product/31044-ban-phim-khong-day-bluetooth-logitech-pebble-keys-2-k380s-tonal-white-920-011754-philong--3-.jpg',
                'short_description' => 'Kết nối: Bluetooth Low Engergy, tương thích với USB Logi Bolt (không đi kèm, phải mua rời)Hỗ trợ kết nối lên đến 3 thiết bị, chuyển đổi dễ dàng Easy-Switch.Có đèn LED báo mức pin. Công tắc bật/tắt bên cạnh phímCác phím chức năng có thể tùy chỉnh thông qua ứng dụng Logi Option+Sử dụng 2 pin AAA Alkaline, thời lượng pin lên đến 36 tháng',
                'detailed_description' => 'Kết nối: Bluetooth Low Engergy, tương thích với USB Logi Bolt (không đi kèm, phải mua rời)Hỗ trợ kết nối lên đến 3 thiết bị, chuyển đổi dễ dàng Easy-Switch.Có đèn LED báo mức pin. Công tắc bật/tắt bên cạnh phímCác phím chức năng có thể tùy chỉnh thông qua ứng dụng Logi Option+Sử dụng 2 pin AAA Alkaline, thời lượng pin lên đến 36 tháng',
                'quantity' => 4,
                'status' => 1,
                'price_sell' => 1050000 / 24000,
                'price_discount' => 990000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Bàn phím cơ không dây CIDOO V65 Dual Mode Matt Grey Switch (USB-C, Bluetooth, Vỏ nhôm CNC)',
                'slug_product' => 'ban-phim-co-khong-day-cidoo-v65-dual-mode-matt-grey-switch-usb-c-bluetooth-vo-nhom-cnc',
                'picture' => 'https://philong.com.vn/media/product/30724-ban-phim-co-khong-day-cidoo-v65-dual-mode-matt-grey-switch-philong--1-.jpg',
                'short_description' => 'Layout 60%, Có núm xoay chỉnh âm lượng2 chế độ kết nối: Cáp USB-C, BluetoothKeycap: PBT Dyesub, Cherry profileMạch xuôi, gasket mount, hỗ trợ hotswap thay switch dễ dàngSwitch: Cidoo Matt GreyPin: 3000mAh; Led: RGB',
                'detailed_description' => 'Layout 60%, Có núm xoay chỉnh âm lượng2 chế độ kết nối: Cáp USB-C, BluetoothKeycap: PBT Dyesub, Cherry profileMạch xuôi, gasket mount, hỗ trợ hotswap thay switch dễ dàngSwitch: Cidoo Matt GreyPin: 3000mAh; Led: RGB',
                'quantity' => 15,
                'status' => 1,
                'price_sell' => 3790000 / 24000,
                'price_discount' => 2790000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 10,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Bàn phím không dây Logitech MX Keys S Graphite (920-011563) (Bluetooth, USB 2.4Ghz Logi Bolt, Kết nối 3 thiết bị, Pin 5 tháng)',
                'slug_product' => 'ban-phim-khong-day-logitech-mx-keys-s-graphite-920-011563-bluetooth-usb-24ghz-logi-bolt-ket-noi-3-thiet-bi-pin-5-thang',
                'picture' => 'https://philong.com.vn/media/product/30705-ban-phim-khong-day-logitech-mx-keys-s-graphite-920-011563-philong--4-.jpg',
                'short_description' => 'Loại sản phẩm: Bàn phím không dây cao cấpKết nối: USB 2.4Ghz Logi Bolt, Bluetooth Low EngeryThời lượng pin: Lên đến 5 tháng (tắt đèn bàn phím), 10 ngày (bật đèn bàn phím)Kết nối lên đến 3 thiết bịTương thích: Windows, macOS, iPadOS, ChromeOS, Linux',
                'detailed_description' => 'Loại sản phẩm: Bàn phím không dây cao cấpKết nối: USB 2.4Ghz Logi Bolt, Bluetooth Low EngeryThời lượng pin: Lên đến 5 tháng (tắt đèn bàn phím), 10 ngày (bật đèn bàn phím)Kết nối lên đến 3 thiết bịTương thích: Windows, macOS, iPadOS, ChromeOS, Linux',
                'quantity' => 12,
                'status' => 1,
                'price_sell' => 2990000 / 24000,
                'price_discount' => 2890000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Bàn phím cơ không dây FL-Esports CMK75SAM Lake Placid Blue, FLCMMK Ice Pink Switch (3 mode, Hotswap, Gasket mount, Núm xoay, Màn hiển thị, Led RGB)',
                'slug_product' => 'ban-phim-co-khong-day-fl-esports-cmk75sam-lake-placid-blue-flcmmk-ice-pink-switch-3-mode-hotswap-gasket-mount-num-xoay-man-hien-thi-led-rgb',
                'picture' => 'https://philong.com.vn/media/product/30490-ban-phim-co-fl-esports-cmk75sam-lake-placid-blue-philong--2-.jpg',
                'short_description' => 'Layout 75%, 82 nút phím (81 phím + 1 núm xoay)3 chế độ kết nối: USB, 2.4GHz, BluetoothKeycap: PBT doubleshot, FSA profileMạch xuôi, Gasket Mount, Plate PC, Trang bị sẵn đệm tiêu âmSwitch: FLCMMK Ice Pink, Hỗ trợ Hot SwapPin: 3000mAh, Led: RGB',
                'detailed_description' => 'Layout 75%, 82 nút phím (81 phím + 1 núm xoay)3 chế độ kết nối: USB, 2.4GHz, BluetoothKeycap: PBT doubleshot, FSA profileMạch xuôi, Gasket Mount, Plate PC, Trang bị sẵn đệm tiêu âmSwitch: FLCMMK Ice Pink, Hỗ trợ Hot SwapPin: 3000mAh, Led: RGB',
                'quantity' => 20,
                'status' => 1,
                'price_sell' => 2590000 / 24000,
                'price_discount' => 2490000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Bàn phím cơ không dây Asus ROG Azoth (NX Red Switch, USB-C, Bluetooth 5.1, RF 2.4GHz)',
                'slug_product' => 'ban-phim-co-khong-day-asus-rog-azoth-nx-red-switch-usb-c-bluetooth-51-rf-24ghz',
                'picture' => 'https://philong.com.vn/media/product/29705-phi-long-rog-azoth-01.jpg',
                'short_description' => 'Thiết kế gasket mount silicone độc đáo với ba lớp bọt giảm chấn tạo ra trải nghiệm gõ phím tuyệt vờiKết nối 3 chế độ: USB 2.0, Bluetooth 5.1, RF 2.4GHz (công nghệ không dây ROG SpeedNova)Layout 75 phím. Màn hình OLED và điều khiển trực quanSwitch cơ học ROG NX (Red, Blue. Brown) có thể thay thế (Hot-swappable), keycap PBT double shot ROG cao cấpBao gồm các sản phẩm dầu bôi trơn Krytox™ GPL-205-GD0 hỗ trợ cho người mới bắt đầu DIY bàn phímThiết kế tiện dụng: Hai cặp chân bàn phím với độ cao khác nhau cung cấp đến ba vị trí nghiêng khác nhauHỗ trợ MacOS: Dễ dàng chuyển đổi giữa chế độ Windows và MacOS',
                'detailed_description' => 'Thiết kế gasket mount silicone độc đáo với ba lớp bọt giảm chấn tạo ra trải nghiệm gõ phím tuyệt vờiKết nối 3 chế độ: USB 2.0, Bluetooth 5.1, RF 2.4GHz (công nghệ không dây ROG SpeedNova)Layout 75 phím. Màn hình OLED và điều khiển trực quanSwitch cơ học ROG NX (Red, Blue. Brown) có thể thay thế (Hot-swappable), keycap PBT double shot ROG cao cấpBao gồm các sản phẩm dầu bôi trơn Krytox™ GPL-205-GD0 hỗ trợ cho người mới bắt đầu DIY bàn phímThiết kế tiện dụng: Hai cặp chân bàn phím với độ cao khác nhau cung cấp đến ba vị trí nghiêng khác nhauHỗ trợ MacOS: Dễ dàng chuyển đổi giữa chế độ Windows và MacOS',
                'quantity' => 2,
                'status' => 1,
                'price_sell' => 799000 / 24000,
                'price_discount' => 699000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Bàn phím cơ E-DRA EK387L White Huano Blue switch, 87 phím, Blue LED',
                'slug_product' => 'ban-phim-co-e-dra-ek387l-white-huano-blue-switch-87-phim-blue-led',
                'picture' => 'https://philong.com.vn/media/product/29746-phi-long-ban-phim-co-e-dra-ek387l-white-huano-blue-switch.jpg',
                'short_description' => 'Số lượng phím: 87 phímTop cover: ABS, Bottom cover: ABSKeycap: Double injection key capsLaser Logo - full antishosting keysSwitch Huano: Blue Sw, Brown Sw, Red Sw',
                'detailed_description' => 'Số lượng phím: 87 phímTop cover: ABS, Bottom cover: ABSKeycap: Double injection key capsLaser Logo - full antishosting keysSwitch Huano: Blue Sw, Brown Sw, Red Sw',
                'quantity' => 4,
                'status' => 1,
                'price_sell' => 750000 / 24000,
                'price_discount' => 650000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Bàn Phím Cơ FL-Esports GP75CPM Polar Night Kailhbox V2 Red Switch (Type C, Bluetooth, Wireless 2.4Ghz)',
                'slug_product' => 'ban-phim-co-fl-esports-gp75cpm-polar-night-kailhbox-v2-red-switch-type-c-bluetooth-wireless-24ghz',
                'picture' => 'https://philong.com.vn/media/product/30089-philong-ban-phim-co-khong-day-e-dra-ek314w-mau-den.jpg',
                'short_description' => '3 chế độ kết nối: USB/2.4/BluetoothCherry doubleshot Keycap, tính năng Hot Swap thay switch dễ dàngLed RGB, SoftwareTrang bị sẵn đệm tiêu âm siliconHỗ trợ hệ điều hành: Windows, MacOS',
                'detailed_description' => '3 chế độ kết nối: USB/2.4/BluetoothCherry doubleshot Keycap, tính năng Hot Swap thay switch dễ dàngLed RGB, SoftwareTrang bị sẵn đệm tiêu âm siliconHỗ trợ hệ điều hành: Windows, MacOS',
                'quantity' => 6,
                'status' => 1,
                'price_sell' => 2290000 / 24000,
                'price_discount' => 2190000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Bàn phím cơ Asus TUF Gaming K7 (Full size, Tactile Switch, USB 2.0, Có kê tay',
                'slug_product' => 'ban-phim-co-asus-tuf-gaming-k7-full-size-tactile-switch-usb-20-co-ke-tay',
                'picture' => 'https://philong.com.vn/media/product/30223-tuf-gaming-k7_2d_aura--1-.png',
                'short_description' => 'Switch cơ quang tiên tiến để kích hoạt chính xác nhanh hơn bàn phím cơ tiêu chuẩn 25 lần và hỗ trợ cả switch dạng tactile lẫn linearĐộ bền chống xâm nhập bụi và nước IP56, bản mặt nhôm cấp độ máy bay và có tuổi thọ gấp đôi so với phím cơ truyền thống để đảm bảo độ tin cậy dài hạnNam châm tích hợp để tháo hoặc lắp tựa kê cổ tay nhanh chóngPhím đèn nền độc lập trang bị công nghệ Aura Sync RGB LEDTạo bản đồ macro theo phím lập trình hoàn toàn, điều chỉnh các thiết lập bằng phần mềm Armoury II',
                'detailed_description' => 'Switch cơ quang tiên tiến để kích hoạt chính xác nhanh hơn bàn phím cơ tiêu chuẩn 25 lần và hỗ trợ cả switch dạng tactile lẫn linearĐộ bền chống xâm nhập bụi và nước IP56, bản mặt nhôm cấp độ máy bay và có tuổi thọ gấp đôi so với phím cơ truyền thống để đảm bảo độ tin cậy dài hạnNam châm tích hợp để tháo hoặc lắp tựa kê cổ tay nhanh chóngPhím đèn nền độc lập trang bị công nghệ Aura Sync RGB LEDTạo bản đồ macro theo phím lập trình hoàn toàn, điều chỉnh các thiết lập bằng phần mềm Armoury II',
                'quantity' => 8,
                'status' => 1,
                'price_sell' => 2990000 / 24000,
                'price_discount' => 1990000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Bàn phím cơ không dây E-DRA EK314W Màu đen, Red switch (104 phím, Wireless 2.4GHz, Bluetooth, E-dra Switch)',
                'slug_product' => 'ban-phim-co-khong-day-e-dra-ek314w-mau-den-red-switch-104-phim-wireless-24ghz-bluetooth-e-dra-switch',
                'picture' => 'https://philong.com.vn/media/product/30089-philong-ban-phim-co-khong-day-e-dra-ek314w-mau-den.jpg',
                'short_description' => 'Kết nối: Wireless 2.4G, BluetoothKeycaps: ABS',
                'detailed_description' => 'Layout: 104 phímSwitch: E-dra Switch (Blue / Red / Brown)Đèn nền: Không',
                'quantity' => 6,
                'status' => 1,
                'price_sell' => 599000 / 24000,
                'price_discount' => 499000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 6,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Bàn phím cơ Gaming không dây Logitech G Pro X TKL LIGHTSPEED White, GX Tactile Switch (920-012149)',
                'slug_product' => 'ban-phim-co-gaming-khong-day-logitech-g-pro-x-tkl-lightspeed-white-gx-tactile-switch-920-012149',
                'picture' => 'https://philong.com.vn/media/product/31127-ban-phim-co-khong-day-logitech-g-pro-x-tkl-lightspeed-white-920-012149-philong--1-.jpg',
                'short_description' => 'Kết nối Bluetooth Wireless với công nghệ LIGHTSPEED cho tốc độ phản hồi chỉ 1msSử dụng Switch GX Tactile độc quyền của LogitechCông nghệ LIGHTSYNC RGB 16.8 triệu màu mang lại cảm giác đồng điệu về hình ảnh và âm thanh với trò chơiThời lượng pin lên đến 50 giờ cho một lần sạc đầy12 phím F có thể lập trìnhKhoảng cách hành trình: 1.9 mm - 2.0 mm2 tùy chọn màu sắc: Đen/Trắng',
                'detailed_description' => 'Kết nối Bluetooth Wireless với công nghệ LIGHTSPEED cho tốc độ phản hồi chỉ 1msSử dụng Switch GX Tactile độc quyền của LogitechCông nghệ LIGHTSYNC RGB 16.8 triệu màu mang lại cảm giác đồng điệu về hình ảnh và âm thanh với trò chơiThời lượng pin lên đến 50 giờ cho một lần sạc đầy12 phím F có thể lập trìnhKhoảng cách hành trình: 1.9 mm - 2.0 mm2 tùy chọn màu sắc: Đen/Trắng',
                'quantity' => 6,
                'status' => 1,
                'price_sell' => 5790000 / 24000,
                'price_discount' => 4790000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Bàn phím cơ DareU EK75 Pro Triple Mode Black Golden - DareU Dream Switch (USB-C, Bluetooth, Wireless 2.4G, 80 phím, Núm xoay, Keycap PBT, Led viền 2 bên)',
                'slug_product' => 'ban-phim-co-dareu-ek75-pro-triple-mode-black-golden-dareu-dream-switch-usb-c-bluetooth-wireless-24g-80-phim-num-xoay-keycap-pbt-led-vien-2-ben',
                'picture' => 'https://philong.com.vn/media/product/30991-ban-phim-co-dareu-ek75-pro-triple-mode-black-golden-dareu-dream-switch-philong--1-.jpg',
                'short_description' => 'Layout: 75% (80 phím + 1 núm xoay)Kết nối: USB-C, Bluetooth, Wireless 2.4GHzSwitch: DareU Dream SwitchKeycap: PBT Doubleshot, OEM profileLed RGB, Có led gầm 2 bên; Pin 3750mAhTính năng khác: Gasket mount, Hotswap 5 pin',
                'detailed_description' => 'Layout: 75% (80 phím + 1 núm xoay)Kết nối: USB-C, Bluetooth, Wireless 2.4GHzSwitch: DareU Dream SwitchKeycap: PBT Doubleshot, OEM profileLed RGB, Có led gầm 2 bên; Pin 3750mAhTính năng khác: Gasket mount, Hotswap 5 pin',
                'quantity' => 30,
                'status' => 1,
                'price_sell' => 1290000 / 24000,
                'price_discount' => 1190000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Bàn phím không dây Bluetooth Logitech Pebble Keys 2 K380s, Tonal Rose (920-011755)',
                'slug_product' => 'ban-phim-khong-day-bluetooth-logitech-pebble-keys-2-k380s-tonal-rose-920-011755',
                'picture' => '	https://philong.com.vn/media/product/30089-philong-ban-phim-co-khong-day-e-dra-ek314w-mau-den.jpg',
                'short_description' => 'Kết nối: Bluetooth Low Engergy, tương thích với USB Logi Bolt (không đi kèm, phải mua rời)Hỗ trợ kết nối lên đến 3 thiết bị, chuyển đổi dễ dàng Easy-Switch.Có đèn LED báo mức pin. Công tắc bật/tắt bên cạnh phímCác phím chức năng có thể tùy chỉnh thông qua ứng dụng Logi Option+Sử dụng 2 pin AAA Alkaline, thời lượng pin lên đến 36 tháng',
                'detailed_description' => 'Kết nối: Bluetooth Low Engergy, tương thích với USB Logi Bolt (không đi kèm, phải mua rời)Hỗ trợ kết nối lên đến 3 thiết bị, chuyển đổi dễ dàng Easy-Switch.Có đèn LED báo mức pin. Công tắc bật/tắt bên cạnh phímCác phím chức năng có thể tùy chỉnh thông qua ứng dụng Logi Option+Sử dụng 2 pin AAA Alkaline, thời lượng pin lên đến 36 tháng',
                'quantity' => 7,
                'status' => 1,
                'price_sell' => 1090000 / 24000,
                'price_discount' => 990000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Bàn phím cơ DareU EK1280S V2 Black - Blue D Switch (104 phím, Multi-led, Led gầm 2 bên, DareU D Switch)',
                'slug_product' => 'ban-phim-co-dareu-ek1280s-v2-black-blue-d-switch-104-phim-multi-led-led-gam-2-ben-dareu-d-switch',
                'picture' => 'https://philong.com.vn/media/product/30878-ban-phim-co-dareu-ek1280s-v2-black-d-switch-philong--1-.jpg',
                'short_description' => 'Phiên bản V2 - Thêm 2 dải LED bên sườnLED nền: RainbowSử dụng Switch D siêu bền của DareUChuẩn layout ANSI, Full size 104 phímKeycap ABS DoubleshotKết nối: Có dây, Cáp dài 1.8mN-Key Rollover: Có',
                'detailed_description' => 'Phiên bản V2 - Thêm 2 dải LED bên sườnLED nền: RainbowSử dụng Switch D siêu bền của DareUChuẩn layout ANSI, Full size 104 phímKeycap ABS DoubleshotKết nối: Có dây, Cáp dài 1.8mN-Key Rollover: Có',
                'quantity' => 8,
                'status' => 1,
                'price_sell' => 890000 / 24000,
                'price_discount' => 790000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Bàn phím quang cơ DareU EK810X Black-Grey Optical Blue Switch (104 phím, ABS Keycap, Multiled, Chống nước)',
                'slug_product' => 'ban-phim-quang-co-dareu-ek810x-black-grey-optical-blue-switch-104-phim-abs-keycap-multiled-chong-nuoc',
                'picture' => '	https://philong.com.vn/media/product/30089-philong-ban-phim-co-khong-day-e-dra-ek314w-mau-den.jpg',
                'short_description' => 'Sử dụng switch Quang học cao cấpChống nước tuyệt đốiMulti-LED - 7 màu chia theo vùngKeycap ABS Doubleshot siêu bềnThiết kế cổ điển, siêu chắc chắn',
                'detailed_description' => 'Sử dụng switch Quang học cao cấpChống nước tuyệt đốiMulti-LED - 7 màu chia theo vùngKeycap ABS Doubleshot siêu bềnThiết kế cổ điển, siêu chắc chắn',
                'quantity' => 1,
                'status' => 1,
                'price_sell' => 890000 / 24000,
                'price_discount' => 790000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Bàn Phím Cơ FL-Esports GP75CPM Polar Night Kailhbox V2 Red Switch (Type C, Bluetooth, Wireless 2.4Ghz)',
                'slug_product' => 'ban-phim-co-fl-esports-gp75cpm-polar-night-kailhbox-v2-red-switch-type-c-bluetooth-wireless-24ghz',
                'picture' => '	https://philong.com.vn/media/product/30089-philong-ban-phim-co-khong-day-e-dra-ek314w-mau-den.jpg',
                'short_description' => '3 chế độ kết nối: USB/2.4/BluetoothCherry doubleshot Keycap, tính năng Hot Swap thay switch dễ dàngLed RGB, SoftwareTrang bị sẵn đệm tiêu âm siliconHỗ trợ hệ điều hành: Windows, MacOS',
                'detailed_description' => '3 chế độ kết nối: USB/2.4/BluetoothCherry doubleshot Keycap, tính năng Hot Swap thay switch dễ dàngLed RGB, SoftwareTrang bị sẵn đệm tiêu âm siliconHỗ trợ hệ điều hành: Windows, MacOS',
                'quantity' => 6,
                'status' => 1,
                'price_sell' => 2290000 / 24000,
                'price_discount' => 2190000 / 24000,
                'id_product_type' => 1,
                'id_brand' => 9,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            // Mouse
            [
                'product_name' => 'Chuột gaming có dây Asus TUF M3 Gen II (8000 DPI, IP56, ASUS Antibacterial Guard, 59g siêu nhẹ, Aura RGB)',
                'slug_product' => 'chuot-gaming-co-day-asus-tuf-m3-gen-ii-8000-dpi-ip56-asus-antibacterial-guard-59g-sieu-nhe-aura-rgb',
                'picture' => 'https://philong.com.vn/media/product/31035-chuot-gaming-co-day-asus-tuf-m3-gen-ii-philong--1-.jpg',
                'short_description' => 'Thiết kế công thái học và trọng lượng siêu nhẹ chỉ 59 gram. Thiết kế vỏ đặc biệt dành cho game thủ thuận tay phảiCảm biến quang học 8000 DPI. Cung cấp tính năng theo dõi chính xác đến từng pixel. Nút DPI để chuyển nhanh giữa 4 mức độChống nước và bụi IP56, đảm bảo độ bền lâu dàiVới lớp phủ bảo vệ  ASUS Antibacterial Guard giúp ngăn chặn sự phát triển của vi khuẩn để bề mặt và các nút của chuột luôn được vệ sinhFeet chuột PTFE đảm bảo di chuyển nhanh và mượt màTùy chọn linh hoạt với 6 nút có thể lập trình và 3 cấu hình bộ nhớ tích hợpPhần mềm Armoury Crate cho phép cấu hình một cách trực quan và có vô số tùy chọn chiếu sáng',
                'detailed_description' => 'Thiết kế công thái học và trọng lượng siêu nhẹ chỉ 59 gram. Thiết kế vỏ đặc biệt dành cho game thủ thuận tay phảiCảm biến quang học 8000 DPI. Cung cấp tính năng theo dõi chính xác đến từng pixel. Nút DPI để chuyển nhanh giữa 4 mức độChống nước và bụi IP56, đảm bảo độ bền lâu dàiVới lớp phủ bảo vệ  ASUS Antibacterial Guard giúp ngăn chặn sự phát triển của vi khuẩn để bề mặt và các nút của chuột luôn được vệ sinhFeet chuột PTFE đảm bảo di chuyển nhanh và mượt màTùy chọn linh hoạt với 6 nút có thể lập trình và 3 cấu hình bộ nhớ tích hợpPhần mềm Armoury Crate cho phép cấu hình một cách trực quan và có vô số tùy chọn chiếu sáng',
                'quantity' => 9,
                'status' => 1,
                'price_sell' => 590000 / 24000,
                'price_discount' => 490000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Chuột gaming có dây ASUS TUF M4 Air (16000 DPI, IPX6, Trọng lượng siêu nhẹ chỉ 47g)',
                'slug_product' => 'chuot-gaming-co-day-asus-tuf-m4-air-16000-dpi-ipx6-trong-luong-sieu-nhe-chi-47g',
                'picture' => 'https://philong.com.vn/media/product/27785-chuot-choi-game-sieu-nhe-asus-tuf-m4-air-philong--1-.jpg',
                'short_description' => 'Cảm biến quang học 16.000 dpi chuẩn gaming để di chuột chính xác từng điểm ảnh, cùng với nút chỉnh DPI 4 cấp độThiết kế Vỏ Air Shell chỉ 47 gram siêu bền và siêu nhẹLớp phủ bảo vệ chống thấm nước IPX6 trên cụm bảng mạch in (PCBA) bảo vệ khỏi sự cố tràn nước và môi trường ẩm thấpLớp bảo vệ kháng khuẩn của ASUS (ASUS Antibacteria Guard)  có tác dụng ức chế sự phát triển của vi khuẩn để giữ cho bề mặt chuột và các nút luôn sạch sẽ và giữ vệ sinhDây dù TUF Gaming Paracord siêu nhẹ, linh hoạt, giảm thiểu tối đa sự cố rối dây, mang đến cảm giác như đang sử dụng chuột không dâyFeet chuột làm bằng 100% PTFE có độ ma sát thấp đảm bảo lướt nhanh và mượt6 nút tương tác, có thể lập trình và 3 cấu hình bộ nhớ tích hợp cho phép bạn tùy chỉnhPhần mềm Armory Crate độc quyền cho phép cấu hình dễ dàng và trực quan',
                'detailed_description' => 'Cảm biến quang học 16.000 dpi chuẩn gaming để di chuột chính xác từng điểm ảnh, cùng với nút chỉnh DPI 4 cấp độThiết kế Vỏ Air Shell chỉ 47 gram siêu bền và siêu nhẹLớp phủ bảo vệ chống thấm nước IPX6 trên cụm bảng mạch in (PCBA) bảo vệ khỏi sự cố tràn nước và môi trường ẩm thấpLớp bảo vệ kháng khuẩn của ASUS (ASUS Antibacteria Guard)  có tác dụng ức chế sự phát triển của vi khuẩn để giữ cho bề mặt chuột và các nút luôn sạch sẽ và giữ vệ sinhDây dù TUF Gaming Paracord siêu nhẹ, linh hoạt, giảm thiểu tối đa sự cố rối dây, mang đến cảm giác như đang sử dụng chuột không dâyFeet chuột làm bằng 100% PTFE có độ ma sát thấp đảm bảo lướt nhanh và mượt6 nút tương tác, có thể lập trình và 3 cấu hình bộ nhớ tích hợp cho phép bạn tùy chỉnhPhần mềm Armory Crate độc quyền cho phép cấu hình dễ dàng và trực quan',
                'quantity' => 5,
                'status' => 1,
                'price_sell' => 1100000 / 24000,
                'price_discount' => 990000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Chuột không dây Logitech MX ANYWHERE 3S Màu trắng, Bluetooth+Wireless 2.4GHz, Pin sạc (910-006933), Chính Hãng',
                'slug_product' => 'chuot-khong-day-logitech-mx-anywhere-3s-mau-trang-bluetoothwireless-24ghz-pin-sac-910-006933-chinh-hang',
                'picture' => 'https://philong.com.vn/media/product/30160-philong-chuot-khong-day-logitech-mx-anywhere-3s-mau-trang--4-.jpg',
                'short_description' => 'Loại sản phẩm: Chuột không dâyKết nối: Bluetooth, USB 2.4GHz Logi Bolt (tùy chọn mua thêm, không đi kèm)Cảm biến: Cảm biến quang học Darkfield LaserDPI: 200-8000 DPIPin sạc: 500mAh cho thời lượng pin lên đến 70 ngày, cổng sạc Type C',
                'detailed_description' => 'Loại sản phẩm: Chuột không dâyKết nối: Bluetooth, USB 2.4GHz Logi Bolt (tùy chọn mua thêm, không đi kèm)Cảm biến: Cảm biến quang học Darkfield LaserDPI: 200-8000 DPIPin sạc: 500mAh cho thời lượng pin lên đến 70 ngày, cổng sạc Type C',
                'quantity' => 2,
                'status' => 1,
                'price_sell' => 1990000 / 24000,
                'price_discount' => 1690000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Chuột Gaming không dây Logitech G Pro X Superlight 2 White (910-006640), New 2023',
                'slug_product' => 'chuot-gaming-khong-day-logitech-g-pro-x-superlight-2-white-910-006640-new-2023',
                'picture' => 'https://philong.com.vn/media/product/31098-chuot-khong-day-gaming-logitech-g-pro-x-superlight-2-white-910-006640-philong--1-.jpg',
                'short_description' => 'Kết nối Wireless với công nghệ LIGHTSPEED cho độ phản hồi nhanh hơn 68% so với thế hệ trướcTrọng lượng siêu nhẹ chỉ 60gSwitch bấm LIGHTFORCE kết hợp giữa Cơ học và Quang họcCảm biến: HERO 2. Độ phân giải: 100 – 32,000 DPI (IPS 500+)Thời lượng pin lên đến 95 giờ cho một lần sạc. Cổng sạc mới USB-C so với Micro USB trên thế hệ cũTốc độ phản hồi: 2K (0,5 ms). Tương thích với PowerPlay5 nút có thể lập trình thông qua phần mềm G-HUB',
                'detailed_description' => 'Kết nối Wireless với công nghệ LIGHTSPEED cho độ phản hồi nhanh hơn 68% so với thế hệ trướcTrọng lượng siêu nhẹ chỉ 60gSwitch bấm LIGHTFORCE kết hợp giữa Cơ học và Quang họcCảm biến: HERO 2. Độ phân giải: 100 – 32,000 DPI (IPS 500+)Thời lượng pin lên đến 95 giờ cho một lần sạc. Cổng sạc mới USB-C so với Micro USB trên thế hệ cũTốc độ phản hồi: 2K (0,5 ms). Tương thích với PowerPlay5 nút có thể lập trình thông qua phần mềm G-HUB',
                'quantity' => 4,
                'status' => 1,
                'price_sell' => 3690000 / 24000,
                'price_discount' => 3590000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Chuột có dây DareU EM911 Black (10.000DPI, Cảm biến DareU Bravo, Trọng lượng 72g, Led RGB)',
                'slug_product' => 'chuot-co-day-dareu-em911-black-10000dpi-cam-bien-dareu-bravo-trong-luong-72g-led-rgb',
                'picture' => 'https://philong.com.vn/media/product/31144-chuot-co-day-dareu-em911-black-philong--1-.jpg',
                'short_description' => 'Cảm biến: DareU BRAVO (ATG4090)DPI: 400-10.000Tracking: 150IPSPolling rate: 1000HzSwitch: DAREU (50 triệu lần click)Kết nối: Có dây USB (1.8m)Trọng lượng: 72g +/- 5g”',
                'detailed_description' => 'Cảm biến: DareU BRAVO (ATG4090)DPI: 400-10.000Tracking: 150IPSPolling rate: 1000HzSwitch: DAREU (50 triệu lần click)Kết nối: Có dây USB (1.8m)Trọng lượng: 72g +/- 5g”',
                'quantity' => 6,
                'status' => 1,
                'price_sell' => 490000 / 24000,
                'price_discount' => 390000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Chuột không dây Newmen F900S Dual Mode, Màu xám (Bluetooth 5.0 + USB 2.4GHz, 4000 DPI, Silent, Pin sạc)',
                'slug_product' => 'chuot-khong-day-newmen-f900s-dual-mode-mau-xam-bluetooth-50-usb-24ghz-4000-dpi-silent-pin-sac',
                'picture' => 'https://philong.com.vn/media/product/31225-chuot-khong-day-newmen-f900s-dual-mode-philong--3-.jpg',
                'short_description' => 'Kết nối: Hai chế độ 2.4Ghz & Bluetooth 5.0/3.0, tích hợp công nghệ 99Glass GoPin: Lithium-ion 300mAh, thời gian sử dụng lên đến 2 thángĐộ phân giải : 600/1200/2400/4000 DPISwitch: Kailh 5 triệu lần nhấn, yên tĩnhKích thước: 103x61x39mm. Trọng lượng: 74gCổng sạc: USB Type-C',
                'detailed_description' => 'Kết nối: Hai chế độ 2.4Ghz & Bluetooth 5.0/3.0, tích hợp công nghệ 99Glass GoPin: Lithium-ion 300mAh, thời gian sử dụng lên đến 2 thángĐộ phân giải : 600/1200/2400/4000 DPISwitch: Kailh 5 triệu lần nhấn, yên tĩnhKích thước: 103x61x39mm. Trọng lượng: 74gCổng sạc: USB Type-C',
                'quantity' => 15,
                'status' => 1,
                'price_sell' => 690000 / 24000,
                'price_discount' => 590000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 5,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Chuột có dây DareU LM121 Blue (6400 DPI, Silent Click, RGB)',
                'slug_product' => 'chuot-co-day-dareu-lm121-blue-6400-dpi-silent-click-rgb',
                'picture' => 'https://philong.com.vn/media/product/31146-chuot-co-day-dareu-lm121-blue-philong--1-.jpg',
                'short_description' => 'Chuẩn kết nối: Dây USBĐộ phân giải tối đa: 6400 DPINút bấm Micro switch với độ bền 3 triệu lần nhấnTích hợp viền LED RGB',
                'detailed_description' => 'Chuẩn kết nối: Dây USBĐộ phân giải tối đa: 6400 DPINút bấm Micro switch với độ bền 3 triệu lần nhấnTích hợp viền LED RGB',
                'quantity' => 11,
                'status' => 1,
                'price_sell' => 295000 / 24000,
                'price_discount' => 195000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Chuột máy tính có dây DARE U LM130S, màu đen, Led RGB, 1600DPI, Bảo hành 24 Tháng',
                'slug_product' => 'chuot-co-day-dareu-lm121-blue-6400-dpi-silent-click-rgb',
                'picture' => 'https://philong.com.vn/media/product/27333-mouse-dearu-lm130s-1.JPG',
                'short_description' => 'Chuẩn kết nối: Dây USBĐộ phân giải tối đa: 6400 DPINút bấm Micro switch với độ bền 3 triệu lần nhấnTích hợp viền LED RGB',
                'detailed_description' => 'Chuẩn kết nối: Dây USBĐộ phân giải tối đa: 6400 DPINút bấm Micro switch với độ bền 3 triệu lần nhấnTích hợp viền LED RGB',
                'quantity' => 12,
                'status' => 1,
                'price_sell' => 169000 / 24000,
                'price_discount' => 130000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Chuột không dây Logitech Pebble 2 M350s Tonal Graphite, Bluetooth, 3 thiết bị, 4000 DPI, Silent Touch (910-006988)',
                'slug_product' => 'chuot-khong-day-logitech-pebble-2-m350s-tonal-graphite-bluetooth-3-thiet-bi-4000-dpi-silent-touch-910-006988',
                'picture' => 'https://philong.com.vn/media/product/31040-chuot-khong-day-logitech-pebble-2-m350s-tonal-white-910-006986-philong--1-.jpg',
                'short_description' => 'Kết nối: Bluetooth Low Engergy, tương thích với USB Logi Bolt (không đi kèm, phải mua rời)Hỗ trợ kết nối lên đến 3 thiết bị, chuyển đổi dễ dàng với nút Easy-SwitchCông nghệ Silent Touch loại bỏ 90% tiếng ồn khi nhấpSử dụng 1 pin AA Alkaline, thời lượng pin lên đến 24 thángTrọng lượng chỉ 76gTùy chỉnh với ứng dụng Logi Option+',
                'detailed_description' => 'Kết nối: Bluetooth Low Engergy, tương thích với USB Logi Bolt (không đi kèm, phải mua rời)Hỗ trợ kết nối lên đến 3 thiết bị, chuyển đổi dễ dàng với nút Easy-SwitchCông nghệ Silent Touch loại bỏ 90% tiếng ồn khi nhấpSử dụng 1 pin AA Alkaline, thời lượng pin lên đến 24 thángTrọng lượng chỉ 76gTùy chỉnh với ứng dụng Logi Option+',
                'quantity' => 19,
                'status' => 1,
                'price_sell' => 599000 / 24000,
                'price_discount' => 499000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Chuột Gaming Không Dây ASUS ROG Gladius III Wireless Aimpoint Black',
                'slug_product' => 'chuot-gaming-khong-day-asus-rog-gladius-iii-wireless-aimpoint-black',
                'picture' => 'https://philong.com.vn/media/product/28966-phi-long-chuot-gaming-khong-day-asus-rog-gladius-iii-wireless-aimpoint.jpg',
                'short_description' => 'Kết nối: ROG SpeedNova 2.4GHz, USB, Bluetooth 5.1Cảm biến: ROG AimPoint 36000 DPISwitch: ROG Micro độ bền 70 triệu lần nhấn Socket: ROG Push-fit dễ dàng thay nóng switchTrọng lượng: 79gThời lượng pin: Lên đến 119 giờ',
                'detailed_description' => 'Kết nối: ROG SpeedNova 2.4GHz, USB, Bluetooth 5.1Cảm biến: ROG AimPoint 36000 DPISwitch: ROG Micro độ bền 70 triệu lần nhấn Socket: ROG Push-fit dễ dàng thay nóng switchTrọng lượng: 79gThời lượng pin: Lên đến 119 giờ',
                'quantity' => 7,
                'status' => 1,
                'price_sell' => 3990000 / 24000,
                'price_discount' => 2990000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Chuột Chơi Game Không Dây LOGITECH G502X PLUS BLACK',
                'slug_product' => 'chuot-choi-game-khong-day-logitech-g502x-plus-black',
                'picture' => 'https://philong.com.vn/media/product/28600-philong-chuot-gaming-khong-day-g502x-plus-black.png',
                'short_description' => 'Phiên bản cải tiến của dòng chuột G502Trọng lượng: 106gSử dụng switch LIGHTFORCE mới nhất của Logitech, PTFE FeetCông nghệ LIGHTSPEED mới nhất, tăng 68% tốc độ phản hồi so với thế hệ cũCảm biến HERO 25K, độ phân giải 100 - 25.600 dpiThời lượng pin lên đến 130 tiếng (37 tiếng với RGB), cổng sạc USB-CHỗ trợ lưu được 5 cấu hình',
                'detailed_description' => 'Phiên bản cải tiến của dòng chuột G502Trọng lượng: 106gSử dụng switch LIGHTFORCE mới nhất của Logitech, PTFE FeetCông nghệ LIGHTSPEED mới nhất, tăng 68% tốc độ phản hồi so với thế hệ cũCảm biến HERO 25K, độ phân giải 100 - 25.600 dpiThời lượng pin lên đến 130 tiếng (37 tiếng với RGB), cổng sạc USB-CHỗ trợ lưu được 5 cấu hình',
                'quantity' => 2,
                'status' => 1,
                'price_sell' => 3899000 / 24000,
                'price_discount' => 3490000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ], [
                'product_name' => 'Chuột không dây Logitech MX Master 3S For Mac - Màu trắng xám, 8000 DPI, Bluetooth, Pin sạc (910-006574)',
                'slug_product' => 'chuot-khong-day-logitech-mx-master-3s-for-mac-mau-trang-xam-8000-dpi-bluetooth-pin-sac-910-006574',
                'picture' => 'https://philong.com.vn/media/product/30287-philong-chuot-khong-day-logitech-mx-master-3s-for-mac-mau-trang-xam-910-006574--1-.jpg',
                'short_description' => 'Loại sản phẩm: Chuột không dâyKết nối: Bluetooth, USB 2.4GHz Logi Bolt (tùy chọn mua thêm, không đi kèm)Cảm biến: Cảm biến quang học Darkfield LaserDPI: 200-8000 DPIPin sạc: 500mAh cho thời lượng pin lên đến 70 ngày, cổng sạc Type CCông nghệ: Quiet Clicks - Giảm 90% tiếng ồn; Bánh xe cuộn Magspeed SmartShift cho phép cuộn lên đến 1000 dòng/giâyPhần mềm hỗ trợ: Logi Options+',
                'detailed_description' => 'Loại sản phẩm: Chuột không dâyKết nối: Bluetooth, USB 2.4GHz Logi Bolt (tùy chọn mua thêm, không đi kèm)Cảm biến: Cảm biến quang học Darkfield LaserDPI: 200-8000 DPIPin sạc: 500mAh cho thời lượng pin lên đến 70 ngày, cổng sạc Type CCông nghệ: Quiet Clicks - Giảm 90% tiếng ồn; Bánh xe cuộn Magspeed SmartShift cho phép cuộn lên đến 1000 dòng/giâyPhần mềm hỗ trợ: Logi Options+',
                'quantity' => 2,
                'status' => 1,
                'price_sell' => 2390000 / 24000,
                'price_discount' => 2290000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'product_name' => 'Chuột Chơi Game Có Dây LOGITECH G502X WHITE',
                'slug_product' => 'chuot-choi-game-co-day-logitech-g502x-white',
                'picture' => 'https://philong.com.vn/media/product/28599-philong-chuot-g502x-white.png',
                'short_description' => 'Phiên bản cải tiến của dòng chuột G502Trọng lượng chỉ 89gSử dụng switch LIGHTFORCE mới nhất của Logitech, PTFE FeetCảm biến HERO 25K, độ phân giải 100 - 25.600 dpiHỗ trợ lưu được 5 cấu hìnhBảo hành chính hãng 24 tháng',
                'detailed_description' => 'Phiên bản cải tiến của dòng chuột G502Trọng lượng chỉ 89gSử dụng switch LIGHTFORCE mới nhất của Logitech, PTFE FeetCảm biến HERO 25K, độ phân giải 100 - 25.600 dpiHỗ trợ lưu được 5 cấu hìnhBảo hành chính hãng 24 tháng',
                'quantity' => 5,
                'status' => 1,
                'price_sell' => 1790000 / 24000,
                'price_discount' => 1690000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'product_name' => 'Chuột không dây DARE U LM115G LION (WL 2.4G, 1600DPI, 6 button, 1 pin AA)',
                'slug_product' => 'chuot-khong-day-dare-u-lm115g-lion-wl-24g-1600dpi-6-button-1-pin-aa',
                'picture' => 'https://philong.com.vn/media/product/27345-lm115g-lion-2.png',
                'short_description' => 'Sensor: PAW3512Sóng không dây 2.4GDPI: 800-1200-1600Switch: Silent (3 triệu lần click)Kích thước: 107.5*59.15*38.29mmPin: 01* AA',
                'detailed_description' => 'Sensor: PAW3512Sóng không dây 2.4GDPI: 800-1200-1600Switch: Silent (3 triệu lần click)Kích thước: 107.5*59.15*38.29mmPin: 01* AA',
                'quantity' => 50,
                'status' => 1,
                'price_sell' => 340000 / 24000,
                'price_discount' => 240000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'product_name' => 'Chuột Gaming Không Dây ASUS ROG Chakram X Origin',
                'slug_product' => 'chuot-gaming-khong-day-asus-rog-chakram-x-origin',
                'picture' => 'https://philong.com.vn/media/product/30234-philong-chuot-gaming-khong-day-asus-rog-chakram-x-origin--1-.png',
                'short_description' => 'Cảm biến ROG Ampoint thế hệ mới, độ phân giải lên đến 36000DPI, polling rate lên đến 8000MHzKết nối 3 chế độ: Cáp USB, Bluetooth, RF 2.4 GHz độ trễ thấpCơ chế nút xoay mang lại sự phản hồi nhanh, cảm giác bấm rõ ràngSocket Push-Fit II giúp dễ dàng thay thế switch 3-pin cơ học hoặc 5-pin quang học, kéo dài tuổi thọ của chuộtDi chuyển mượt mà và nhanh chóng với dây dù ROG Paracord và feet chuột 100% PTFECác nút và nắp được gắn với nhau bằng nam châm. Bên cạnh đó là tấm huy hiệu có thể thiết kế logo riêng, cá nhân hóa chuột theo sở thích của mình.Tương thích với công nghệ Reflex Latency Analyzer của NVIDIA để theo dõi khả năng phản hồi của chuột',
                'detailed_description' => 'Cảm biến ROG Ampoint thế hệ mới, độ phân giải lên đến 36000DPI, polling rate lên đến 8000MHzKết nối 3 chế độ: Cáp USB, Bluetooth, RF 2.4 GHz độ trễ thấpCơ chế nút xoay mang lại sự phản hồi nhanh, cảm giác bấm rõ ràngSocket Push-Fit II giúp dễ dàng thay thế switch 3-pin cơ học hoặc 5-pin quang học, kéo dài tuổi thọ của chuộtDi chuyển mượt mà và nhanh chóng với dây dù ROG Paracord và feet chuột 100% PTFECác nút và nắp được gắn với nhau bằng nam châm. Bên cạnh đó là tấm huy hiệu có thể thiết kế logo riêng, cá nhân hóa chuột theo sở thích của mình.Tương thích với công nghệ Reflex Latency Analyzer của NVIDIA để theo dõi khả năng phản hồi của chuột',
                'quantity' => 50,
                'status' => 1,
                'price_sell' => 3670000 / 24000,
                'price_discount' => 3570000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 2,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'product_name' => 'Chuột Apple Magic Mouse Black Multi-Touch (MMMQ3ZA/A)',
                'slug_product' => 'chuot-apple-magic-mouse-black-multi-touch-mmmq3zaa',
                'picture' => 'https://philong.com.vn/media/product/29853-chuot-apple-magic-mouse-mmmq3zaa-philong.png',
                'short_description' => 'Magic Mouse - Black Multi-Touch Surface có thiết kế bề mặt cảm ứng tiện dụng và sang trọng, dễ dàng thực hiện các thao tác như lật trang, keo trang lên xuống...Kết nối không dây bằng bluetoothPin sạc 1 lần có thể sử dụng lên đến 1 thángHệ điều hành tương thích: Bluetooth-enabled Mac with OS X 10.11 or later, iPad with iPadOS 13.4 or laterThiết bị tương thích: iPad mini 4 và các thế hệ iPad mới hơn, Mac mini từ 2014, Mac Pro từ 2013, iMac từ 2014, MacBook Pro từ 2012, MacBook Air từ 2015',
                'detailed_description' => 'Magic Mouse - Black Multi-Touch Surface có thiết kế bề mặt cảm ứng tiện dụng và sang trọng, dễ dàng thực hiện các thao tác như lật trang, keo trang lên xuống...Kết nối không dây bằng bluetoothPin sạc 1 lần có thể sử dụng lên đến 1 thángHệ điều hành tương thích: Bluetooth-enabled Mac with OS X 10.11 or later, iPad with iPadOS 13.4 or laterThiết bị tương thích: iPad mini 4 và các thế hệ iPad mới hơn, Mac mini từ 2014, Mac Pro từ 2013, iMac từ 2014, MacBook Pro từ 2012, MacBook Air từ 2015',
                'quantity' => 1,
                'status' => 1,
                'price_sell' => 2790000 / 24000,
                'price_discount' => 2290000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'product_name' => 'Chuột chơi Game 6 nút LOGITECH G102 LIGHTSYNC màu trắng (8000dpi, RGB sync led)',
                'slug_product' => 'chuot-apple-magic-mouse-black-multi-touch-mmmq3zaa',
                'picture' => 'https://philong.com.vn/media/product/22658-39104_g102_lightsync_white_ha5.jpg',
                'short_description' => 'Windows® 7 trở lên',
                'detailed_description' => 'macOS 10.10 trở lên',
                'quantity' => 3,
                'status' => 1,
                'price_sell' => 599000 / 24000,
                'price_discount' => 430000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 3,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'product_name' => 'Chuột Không Dây DAREU LM115B Màu Hồng (Bluetooth, 2.4GHz, 1600 DPI, Pin AA)',
                'slug_product' => 'chuot-khong-day-dareu-lm115b-mau-hong-bluetooth-24ghz-1600-dpi-pin-aa',
                'picture' => 'https://philong.com.vn/media/product/28961-chuot-khong-day-dareu-lm115b-06.png',
                'short_description' => 'Độ phân giải : 800-1200-1600 DPISwitch bấm silent độ bền ~3 triệu lần nhấnKết nối: Wireless 2.4GHz Nano Receiver + Bluetooth 5.0Kích thước: 107 x 59 x 38 mm',
                'detailed_description' => 'Độ phân giải : 800-1200-1600 DPISwitch bấm silent độ bền ~3 triệu lần nhấnKết nối: Wireless 2.4GHz Nano Receiver + Bluetooth 5.0Kích thước: 107 x 59 x 38 mm',
                'quantity' => 3,
                'status' => 1,
                'price_sell' => 370000 / 24000,
                'price_discount' => 270000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 7,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'product_name' => 'Chuột Gaming có dây Rapoo VT200 Màu đen (6200 DPI, Led RGB)',
                'slug_product' => 'chuot-gaming-co-day-rapoo-vt200-mau-den-6200-dpi-led-rgb',
                'picture' => 'https://philong.com.vn/media/product/31538-chuot-gaming-co-day-rapoo-vt200-mau-den-philong--5-.jpg',
                'short_description' => 'Độ phân giải : 800-1200-1600 DPISwitch bấm silent độ bền ~3 triệu lần nhấnKết nối: Wireless 2.4GHz Nano Receiver + Bluetooth 5.0Kích thước: 107 x 59 x 38 mm',
                'detailed_description' => 'Độ phân giải : 800-1200-1600 DPISwitch bấm silent độ bền ~3 triệu lần nhấnKết nối: Wireless 2.4GHz Nano Receiver + Bluetooth 5.0Kích thước: 107 x 59 x 38 mm',
                'quantity' => 3,
                'status' => 1,
                'price_sell' => 490000 / 24000,
                'price_discount' => 390000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 16,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],[
                'product_name' => 'Chuột Gaming có dây Rapoo V16 RGB Màu đen (12800 DPI, Led RGB)',
                'slug_product' => 'chuot-gaming-co-day-rapoo-v16-rgb-mau-den-12800-dpi-led-rgb',
                'picture' => 'https://philong.com.vn/media/product/31537-chuot-gaming-co-day-rapoo-v16-rgb-mau-den-philong--1-.png',
                'short_description' => 'Độ phân giải : 800-1200-1600 DPISwitch bấm silent độ bền ~3 triệu lần nhấnKết nối: Wireless 2.4GHz Nano Receiver + Bluetooth 5.0Kích thước: 107 x 59 x 38 mm',
                'detailed_description' => 'Độ phân giải : 800-1200-1600 DPISwitch bấm silent độ bền ~3 triệu lần nhấnKết nối: Wireless 2.4GHz Nano Receiver + Bluetooth 5.0Kích thước: 107 x 59 x 38 mm',
                'quantity' => 3,
                'status' => 1,
                'price_sell' => 590000 / 24000,
                'price_discount' => 290000 / 24000,
                'id_product_type' => 2,
                'id_brand' => 18,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
