@extends('client.master')
@section('content')
    <div>
        @include('client.component.topseller')
        @include('client.component.service')
    </div>
@endsection
@section('js')
    <script>
    </script>
@endsection
